# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='phone.proto',
  package='main',
  serialized_pb=_b('\n\x0bphone.proto\x12\x04main\"A\n\x04User\x12\r\n\x05index\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x1c\n\x07\x63ontent\x18\x03 \x02(\x0b\x32\x0b.main.Phone\"*\n\x05Phone\x12\x11\n\tphoneType\x18\x01 \x02(\t\x12\x0e\n\x06number\x18\x02 \x02(\x05\"\x16\n\x06Remark\x12\x0c\n\x04note\x18\x01 \x02(\t*.\n\tPhoneType\x12\r\n\tTelephone\x10\x00\x12\x08\n\x04Home\x10\x01\x12\x08\n\x04Work\x10\x02')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_PHONETYPE = _descriptor.EnumDescriptor(
  name='PhoneType',
  full_name='main.PhoneType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Telephone', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Home', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Work', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=156,
  serialized_end=202,
)
_sym_db.RegisterEnumDescriptor(_PHONETYPE)

PhoneType = enum_type_wrapper.EnumTypeWrapper(_PHONETYPE)
Telephone = 0
Home = 1
Work = 2



_USER = _descriptor.Descriptor(
  name='User',
  full_name='main.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='main.User.index', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='main.User.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='content', full_name='main.User.content', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=86,
)


_PHONE = _descriptor.Descriptor(
  name='Phone',
  full_name='main.Phone',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phoneType', full_name='main.Phone.phoneType', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='main.Phone.number', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=130,
)


_REMARK = _descriptor.Descriptor(
  name='Remark',
  full_name='main.Remark',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='note', full_name='main.Remark.note', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=154,
)

_USER.fields_by_name['content'].message_type = _PHONE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['Phone'] = _PHONE
DESCRIPTOR.message_types_by_name['Remark'] = _REMARK
DESCRIPTOR.enum_types_by_name['PhoneType'] = _PHONETYPE

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'phone_pb2'
  # @@protoc_insertion_point(class_scope:main.User)
  ))
_sym_db.RegisterMessage(User)

Phone = _reflection.GeneratedProtocolMessageType('Phone', (_message.Message,), dict(
  DESCRIPTOR = _PHONE,
  __module__ = 'phone_pb2'
  # @@protoc_insertion_point(class_scope:main.Phone)
  ))
_sym_db.RegisterMessage(Phone)

Remark = _reflection.GeneratedProtocolMessageType('Remark', (_message.Message,), dict(
  DESCRIPTOR = _REMARK,
  __module__ = 'phone_pb2'
  # @@protoc_insertion_point(class_scope:main.Remark)
  ))
_sym_db.RegisterMessage(Remark)


# @@protoc_insertion_point(module_scope)
