# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pro_py.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pro_py.proto',
  package='infos',
  serialized_pb=_b('\n\x0cpro_py.proto\x12\x05infos\"#\n\x06Person\x12\x0b\n\x03\x61ge\x18\x02 \x02(\x05\x12\x0c\n\x04name\x18\x03 \x02(\t\"0\n\x03One\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1d\n\x06person\x18\x02 \x02(\x0b\x32\r.infos.Person\")\n\x03Two\x12\t\n\x01x\x18\x01 \x02(\r\x12\x17\n\x03one\x18\x02 \x02(\x0b\x32\n.infos.One\"+\n\x05Three\x12\t\n\x01y\x18\x01 \x02(\r\x12\x17\n\x03two\x18\x02 \x02(\x0b\x32\n.infos.Two')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERSON = _descriptor.Descriptor(
  name='Person',
  full_name='infos.Person',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='age', full_name='infos.Person.age', index=0,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='infos.Person.name', index=1,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=58,
)


_ONE = _descriptor.Descriptor(
  name='One',
  full_name='infos.One',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='infos.One.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='person', full_name='infos.One.person', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=108,
)


_TWO = _descriptor.Descriptor(
  name='Two',
  full_name='infos.Two',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='infos.Two.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='one', full_name='infos.Two.one', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=151,
)


_THREE = _descriptor.Descriptor(
  name='Three',
  full_name='infos.Three',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='y', full_name='infos.Three.y', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='two', full_name='infos.Three.two', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=196,
)

_ONE.fields_by_name['person'].message_type = _PERSON
_TWO.fields_by_name['one'].message_type = _ONE
_THREE.fields_by_name['two'].message_type = _TWO
DESCRIPTOR.message_types_by_name['Person'] = _PERSON
DESCRIPTOR.message_types_by_name['One'] = _ONE
DESCRIPTOR.message_types_by_name['Two'] = _TWO
DESCRIPTOR.message_types_by_name['Three'] = _THREE

Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), dict(
  DESCRIPTOR = _PERSON,
  __module__ = 'pro_py_pb2'
  # @@protoc_insertion_point(class_scope:infos.Person)
  ))
_sym_db.RegisterMessage(Person)

One = _reflection.GeneratedProtocolMessageType('One', (_message.Message,), dict(
  DESCRIPTOR = _ONE,
  __module__ = 'pro_py_pb2'
  # @@protoc_insertion_point(class_scope:infos.One)
  ))
_sym_db.RegisterMessage(One)

Two = _reflection.GeneratedProtocolMessageType('Two', (_message.Message,), dict(
  DESCRIPTOR = _TWO,
  __module__ = 'pro_py_pb2'
  # @@protoc_insertion_point(class_scope:infos.Two)
  ))
_sym_db.RegisterMessage(Two)

Three = _reflection.GeneratedProtocolMessageType('Three', (_message.Message,), dict(
  DESCRIPTOR = _THREE,
  __module__ = 'pro_py_pb2'
  # @@protoc_insertion_point(class_scope:infos.Three)
  ))
_sym_db.RegisterMessage(Three)


# @@protoc_insertion_point(module_scope)
