log:
  file_name: default.log
  level:
    console_level: DEBUG
    file_level: INFO
  format:
    console_fmt: '%(log_color)s%(asctime)s - %(filename)s - line:%(lineno)d - [%(levelname)s]: %(message)s'
    file_fmt: '%(asctime)s - %(filename)s - [%(levelname)s] - %(message)s'
  backupCount: 5
  when: S
  regular: '^\w{7}\.\w{3}\.\d{4}-\d{2}-\d{2}_\d{2}-\d{2}-\d{2}(\.\w+)?$'


